version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.2.4

jobs:
  tests:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-yarn
      - run: node --version
      - run: yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint
      - run: yarn cover
      - codecov:
          file: coverage/*.json

workflows:
  ci:
    jobs:
      - tests
