version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.0.0

jobs:
  tests:
    docker:
      - image: cimg/node:16.10-browsers
    steps:
      - checkout
      - node/install-yarn
      - run:
          name: Show Node version]
          command: |
            node --version
            yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run lint check
          command: yarn lint
      - run:
          name: Run unit tests with coverage
          command: yarn cover
      - codecov/upload:
          file: coverage/*.json
      - run:
          name: Publish to Chromatic
          command: yarn chromatic --project-token=${CHROMATIC_TOKEN}
  versioning:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Check package version
          command: node scripts/check-version edmilsondmx projeto_autoescola

workflows:
  ci:
    jobs:
      - tests
      - versioning:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
